### ISSUE TITLE
FailedConnectionException2

### ISSUE THREAD

**Issue by dubov94** [agsh/mipt15-1#1]
В Windows 8 на Haskell возникает следующая ошибка:

`*** Exception: FailedConnectionException2 "mipt.eu01.aws.af.cm" 80 False getAddrInfo: does not exist (error 10093)`

Лечится использованием Network.withSocketsDo: `main = withSocketsDo $ do`.

**Comment by agsh** [comment]
Да, спасибо, это на всех windows так, постоянно забываю.
