### ISSUE TITLE
Извлечение информации о поддерживаемых парадигмах (вариант 1)

### ISSUE THREAD

**Issue by yanykin** [agsh/mipt15-1#5]
Верно ли я понимаю, что задание предполагает для каждого языка в перечисленном на странице списке будет грузиться соответствующая страница из Википедии, и путём некоторых придуманных эвристик определять текстовые признаки, отвечающие за присутствие тех или иных парадигм? Например, наличие/количество/положение токенов `imperative` и/или `functional`.

**Comment by agsh** [comment]
Ответил в письме.
