### ISSUE TITLE
Лаб. 2. Вар. 6

### ISSUE THREAD

**Issue by sautin1** [agsh/mipt15-1#7]
При попытке отправить решение второй лабы (парсинг html) получаю ответ:
Lab2: StatusCodeException (Status {statusCode = 413, statusMessage = "Request Entity Too Large"})...
Вы не могли бы увеличить возможный размер принимаемых запросов?

Я присылаю ответ в формате:
["name: <ФИО преподавателя>\n
vk: <ссылка ВК>\n
fb: <ссылка FB>\n
lIn: <ссылка LinkedIn>\n", ...]

В итоге файл с результатом работы программы весит около 110 Кб, при этом вывод корректен (отвечает требуемому в задаче).

**Comment by agsh** [comment]
Увеличил размер приёма сырого сообщения в urlencoded до 2 мегабайт, должно хватить. Можно проверять.
