### ISSUE TITLE
Лабораторная 0

### ISSUE THREAD

**Issue by annoing-morda** [agsh/mipt15-1#9]
При запуске программы (Haskell) выбрасывается исключение:
lab0: StatusCodeException (Status {statusCode = 404, statusMessage = "Not Found"}) [("Accept-Ranges","bytes"),("Age","0"),("Content-Type","text/html; charset=utf-8"),("Date","Sat, 16 May 2015 14:56:51 GMT"),("Server","nginx"),("set-cookie","connect.sid=s%3AAkW0exOd14GLuHZXj9FbvF55CKTXYD7u.MEOqxjuG0wc847y9NVirZe2Yja1hADTX3TKdRur3dbk; Path=/; HttpOnly"),("Via","1.1 varnish"),("X-Content-Type-Options","nosniff"),("X-Powered-By","Express"),("X-Varnish","1170417170"),("Content-Length","18"),("Connection","keep-alive"),("X-Response-Body-Start","Cannot POST /lab0\n"),("X-Request-URL","POST http://mipt.eu01.aws.af.cm:80/lab0")](CJ {expose = [Cookie {cookie_name = "connect.sid", cookie_value = "s%3AAkW0exOd14GLuHZXj9FbvF55CKTXYD7u.MEOqxjuG0wc847y9NVirZe2Yja1hADTX3TKdRur3dbk", cookie_expiry_time = 3014-09-16 00:00:00 UTC, cookie_domain = "mipt.eu01.aws.af.cm", cookie_path = "/", cookie_creation_time = 2015-05-16 14:55:18.570088 UTC, cookie_last_access_time = 2015-05-16 14:55:18.570088 UTC, cookie_persistent = False, cookie_host_only = True, cookie_secure_only = False, cookie_http_only = True}]})

**Comment by agsh** [comment]
Хороший вопрос. Регистрация, она же лаба 0, закрылась месяца 2 назад, после того так записались все желающие. Поэтому и 404 ошибка. И сроки сдачи первой лабы тоже прошли. Этот курс для тебя обязательный?

**Comment by annoing-morda** [comment]
Да. Я могу хотя бы получить вариант для остальных лаб?

**Comment by agsh** [comment]
Ok, вариант пусть будет 15, а проверка-сдача на самом зачёте
